
env:
  X: Y

test_task:
  container:
    matrix:
      - image: teeks99/gcc-ubuntu:latest
      - image: teeks99/clang-ubuntu:latest
  test_script:
    - apt update && apt install -y cmake git
    - mkdir build && cd build && cmake -DSELF_TEST_ENABLE=ON .. && make && ctest