env: X=Y

compiler: gcc

language: cpp

#install: make ninja cmake get-deps

# script: skip

jobs:
  include:
    - script: 'mkdir build && cd build && cmake -DSELF_TEST_ENABLE=ON .. && make && ctest'